// Ilova ichidagi interfeys matnlari (1-bosqich: navigatsiya, hisob menyusi,
// asosiy mashq/imtihon oqimi). Nemis tili — asl matn va zaxira (fallback).
// Boshqa sahifalar (Arztbrief, Kollege, Befund, Aussprache, Partner, Coach,
// Daily, Home tool grid) keyingi bosqichda qo'shiladi — hozircha nemis tilida qoladi.

export const APP_UI = {
  de: {
    navHome: 'Start', navPractice: 'Üben', navToday: 'Heute', navMistakes: 'Fehler', navCoach: 'Coach',
    account: 'Konto', changeAvatar: 'Profilbild ändern',
    loggedInAs: 'Angemeldet als', memberSince: 'Mitglied seit', daysUnit: 'Tage', practicedOn: 'Geübt an', daysUnit2: 'Tagen',
    targetState: 'Ziel-Bundesland', myMistakes: 'Meine Fehler', dailyTraining: '10-Minuten-Training',
    aiCoach: 'AI-Lerncoach', dashboard: 'Dashboard', logout: 'Abmelden',
    practiceAccount: 'Praxiskonto', level: 'Stufe', practicedDaysTitle: 'An diesen Tagen geübt',

    diffLeicht: 'Leicht', diffMittel: 'Mittel', diffSchwer: 'Schwer', diffPro: 'Pro',
    nextPatient: 'Nächster Patient →', newCase: '✨ Neuer Fall', caseCreating: 'Fall wird erstellt…',
    voiceActive: '🎙️ Sprachgespräch: Aktiv', voiceStart: '🎙️ Sprachgespräch starten',
    talkDone: '⏹ Fertig', talkSpeak: '🎤 Sprechen',
    patientSpeaking: 'Patient spricht…', recording: 'Aufnahme läuft…', transcribing: 'Wird verstanden…',
    listening: 'Ich höre zu…', oneMoment: 'Einen Moment…',
    voiceHintPtt: 'Tippen Sie auf „Sprechen", sprechen Sie, und tippen Sie danach auf „Fertig". Z. B. „Können Sie mir ein Röntgenbild schicken?" oder „Meine Diagnose ist …"',
    voiceHintSr: 'Sagen Sie z. B. „Können Sie mir ein Röntgenbild schicken?" oder „Meine Diagnose ist …" — das Gespräch läuft ohne Tastendruck weiter.',
    askPlaceholder: 'Stellen Sie Ihre Frage…', askPlaceholderVoice: 'Sprachmodus aktiv — oder hier tippen…',
    send: 'Senden', requestImage: 'anfordern', xrayNoun: 'Röntgenbild', photoNoun: 'Foto',
    askSendXray: 'Könnten Sie mir bitte ein Röntgenbild schicken?', askSendPhoto: 'Könnten Sie mir bitte ein Foto schicken?',
    imgHint: 'In der Praxis stützt sich die Diagnose meist auf ein Bild — fordern Sie es an, bevor Sie Ihre Diagnose eintragen.',
    yourDiagnosis: 'Ihre Diagnose (Pflichtfeld für die Auswertung)', diagPlaceholder: 'z. B. Irreversible Pulpitis, Zahn 36',
    showEval: 'Auswertung anzeigen', enterDiagFirst: 'Bitte tragen Sie zuerst Ihre Diagnose ein.',
    toothToggleOpen: '🦷 Zahnschema öffnen — Zahn auswählen', toothToggleClose: 'Zahnschema ausblenden',
    evalLoading: 'Auswertung wird erstellt…', diagRight: 'Diagnose richtig', diagWrong: 'Diagnose falsch', diagPartial: 'Diagnose teilweise richtig',
    examTitle: 'Prüfung (20 Fragen)',
    examDesc: 'Sie beantworten alle 20 Fragen. Am Ende sehen Sie Ihr Ergebnis — ab 18 richtigen Antworten haben Sie bestanden und steigen zur nächsten Stufe auf.',
    examStart: 'Prüfung starten', cancel: 'Abbrechen',
    connectionError: 'Verbindungsproblem — bitte erneut versuchen.',
    voiceNothingHeard: 'Nichts verstanden — bitte noch einmal sprechen.',
    voiceRecognitionFailed: 'Spracherkennung fehlgeschlagen. Bitte erneut versuchen.',
    voiceNoMic: 'Kein Mikrofonzugriff. Bitte in den Einstellungen erlauben.',

    quizCreating: 'Die Prüfungsfragen werden für diesen Fall erstellt…',
    quizCreatingSub: 'Das kann bis zu 30 Sekunden dauern — sie werden jedes Mal neu generiert.',
    exam: 'Prüfung', retry: 'Erneut versuchen', backToCase: 'Zurück zum Fall',
    notPassed: 'Nicht bestanden', passed: 'Bestanden', of: 'von',
    passNote: 'Für den Aufstieg sind mindestens {n} von {t} richtigen Antworten nötig. Lesen Sie zuerst, was schiefgelaufen ist:',
    restart: 'Von vorne beginnen', nextStage: 'Weiter zur nächsten Stufe →', repeatStage: 'Diese Stufe wiederholen',
    question: 'Frage', confirmAnswer: 'Antwort bestätigen', next: 'Weiter', finishExam: 'Prüfung abschließen',
    correct: 'Richtig.', incorrect: 'Falsch.',
    yourAnswer: 'Ihre Antwort:', correctWouldBe: 'Richtig wäre:', deepenTopic: 'Thema vertiefen →',
    reviewMistakes: 'Diese Punkte sollten Sie sich trotzdem ansehen:',
    toAccount: 'zum Praxiskonto', xpUnit: 'Erfahrung', levelUp: 'Aufstieg'
  },
  uz: {
    navHome: 'Bosh sahifa', navPractice: 'Mashq', navToday: 'Bugun', navMistakes: 'Xatolar', navCoach: 'Murabbiy',
    account: 'Hisob', changeAvatar: 'Profil rasmini o\'zgartirish',
    loggedInAs: 'Kirilgan hisob', memberSince: 'A\'zo bo\'lgan', daysUnit: 'kun', practicedOn: 'Mashq qilingan', daysUnit2: 'kun',
    targetState: 'Maqsad Bundesland', myMistakes: 'Mening xatolarim', dailyTraining: '10-daqiqalik mashq',
    aiCoach: 'AI-o\'quv murabbiyi', dashboard: 'Boshqaruv paneli', logout: 'Chiqish',
    practiceAccount: 'Amaliyot hisobi', level: 'Daraja', practicedDaysTitle: 'Shu kunlarda mashq qilingan',

    diffLeicht: 'Oson', diffMittel: 'O\'rta', diffSchwer: 'Qiyin', diffPro: 'Pro',
    nextPatient: 'Keyingi bemor →', newCase: '✨ Yangi holat', caseCreating: 'Holat yaratilmoqda…',
    voiceActive: '🎙️ Ovozli suhbat: Faol', voiceStart: '🎙️ Ovozli suhbatni boshlash',
    talkDone: '⏹ Tayyor', talkSpeak: '🎤 Gapirish',
    patientSpeaking: 'Bemor gapiryapti…', recording: 'Yozib olinmoqda…', transcribing: 'Tushunilmoqda…',
    listening: 'Tinglayapman…', oneMoment: 'Bir lahza…',
    voiceHintPtt: '"Gapirish" tugmasini bosing, gapiring, so\'ng "Tayyor" tugmasini bosing. Masalan: "Menga rentgen rasm yubora olasizmi?" yoki "Mening tashxisim — …"',
    voiceHintSr: 'Masalan: "Menga rentgen rasm yubora olasizmi?" yoki "Mening tashxisim — …" deng — suhbat tugma bosmasdan davom etadi.',
    askPlaceholder: 'Savolingizni yozing…', askPlaceholderVoice: 'Ovozli rejim faol — yoki shu yerga yozing…',
    send: 'Yuborish', requestImage: 'so\'rash', xrayNoun: 'Rentgen', photoNoun: 'Foto',
    askSendXray: 'Menga rentgen rasmni yubora olasizmi?', askSendPhoto: 'Menga fotosuratni yubora olasizmi?',
    imgHint: 'Klinikada tashxis odatda rasmga asoslanadi — diagnozni kiritishdan oldin uni so\'rang.',
    yourDiagnosis: 'Sizning tashxisingiz (baholash uchun majburiy)', diagPlaceholder: 'masalan: Irreversibel pulpit, 36-tish',
    showEval: 'Baholashni ko\'rsatish', enterDiagFirst: 'Iltimos, avval tashxisingizni kiriting.',
    toothToggleOpen: '🦷 Tish sxemasini ochish — tish tanlash', toothToggleClose: 'Tish sxemasini yashirish',
    evalLoading: 'Baholash tayyorlanmoqda…', diagRight: 'Tashxis to\'g\'ri', diagWrong: 'Tashxis noto\'g\'ri', diagPartial: 'Tashxis qisman to\'g\'ri',
    examTitle: 'Imtihon (20 savol)',
    examDesc: 'Siz barcha 20 ta savolga javob berasiz. Oxirida natijangizni ko\'rasiz — 18 va undan ko\'p to\'g\'ri javob bilan siz o\'tasiz va keyingi bosqichga chiqasiz.',
    examStart: 'Imtihonni boshlash', cancel: 'Bekor qilish',
    connectionError: 'Ulanish muammosi — qayta urinib ko\'ring.',
    voiceNothingHeard: 'Hech narsa tushunilmadi — yana bir bor gapiring.',
    voiceRecognitionFailed: 'Nutqni tanib bo\'lmadi. Qayta urinib ko\'ring.',
    voiceNoMic: 'Mikrofonga ruxsat yo\'q. Sozlamalardan ruxsat bering.',

    quizCreating: 'Ushbu holat uchun imtihon savollari tuzilmoqda…',
    quizCreatingSub: 'Bu 30 soniyagacha davom etishi mumkin — har safar yangidan yaratiladi.',
    exam: 'Imtihon', retry: 'Qayta urinish', backToCase: 'Holatga qaytish',
    notPassed: 'O\'tilmadi', passed: 'O\'tildi', of: 'dan',
    passNote: 'O\'tish uchun kamida {t} tadan {n} tasi to\'g\'ri kerak. Avval nima xato bo\'lganini o\'qib chiqing:',
    restart: 'Boshidan boshlash', nextStage: 'Keyingi bosqichga →', repeatStage: 'Shu bosqichni takrorlash',
    question: 'Savol', confirmAnswer: 'Javobni tasdiqlash', next: 'Keyingisi', finishExam: 'Imtihonni yakunlash',
    correct: 'To\'g\'ri.', incorrect: 'Noto\'g\'ri.',
    yourAnswer: 'Sizning javobingiz:', correctWouldBe: 'To\'g\'ri javob:', deepenTopic: 'Mavzuni chuqurlashtirish →',
    reviewMistakes: 'Bularni ham ko\'rib chiqing:',
    toAccount: 'amaliyot hisobiga', xpUnit: 'tajriba', levelUp: 'Yangi daraja'
  },
  ru: {
    navHome: 'Главная', navPractice: 'Практика', navToday: 'Сегодня', navMistakes: 'Ошибки', navCoach: 'Коуч',
    account: 'Аккаунт', changeAvatar: 'Изменить фото профиля',
    loggedInAs: 'Вы вошли как', memberSince: 'Участник с', daysUnit: 'дней', practicedOn: 'Практика в течение', daysUnit2: 'дней',
    targetState: 'Целевая федеральная земля', myMistakes: 'Мои ошибки', dailyTraining: '10-минутная тренировка',
    aiCoach: 'ИИ-наставник', dashboard: 'Панель управления', logout: 'Выйти',
    practiceAccount: 'Практический счёт', level: 'Уровень', practicedDaysTitle: 'Дни практики',

    diffLeicht: 'Лёгкий', diffMittel: 'Средний', diffSchwer: 'Сложный', diffPro: 'Про',
    nextPatient: 'Следующий пациент →', newCase: '✨ Новый случай', caseCreating: 'Случай создаётся…',
    voiceActive: '🎙️ Голосовой разговор: активен', voiceStart: '🎙️ Начать голосовой разговор',
    talkDone: '⏹ Готово', talkSpeak: '🎤 Говорить',
    patientSpeaking: 'Пациент говорит…', recording: 'Идёт запись…', transcribing: 'Распознаём…',
    listening: 'Слушаю…', oneMoment: 'Секунду…',
    voiceHintPtt: 'Нажмите «Говорить», скажите фразу, затем нажмите «Готово». Например: «Можете прислать рентген?» или «Мой диагноз — …»',
    voiceHintSr: 'Скажите, например: «Можете прислать рентген?» или «Мой диагноз — …» — разговор продолжается без нажатия кнопок.',
    askPlaceholder: 'Задайте ваш вопрос…', askPlaceholderVoice: 'Голосовой режим активен — или печатайте здесь…',
    send: 'Отправить', requestImage: 'запросить', xrayNoun: 'Рентген', photoNoun: 'Фото',
    askSendXray: 'Не могли бы вы прислать рентгеновский снимок?', askSendPhoto: 'Не могли бы вы прислать фото?',
    imgHint: 'На практике диагноз обычно основан на снимке — запросите его перед постановкой диагноза.',
    yourDiagnosis: 'Ваш диагноз (обязательно для оценки)', diagPlaceholder: 'например: Необратимый пульпит, зуб 36',
    showEval: 'Показать оценку', enterDiagFirst: 'Сначала введите ваш диагноз.',
    toothToggleOpen: '🦷 Открыть схему зубов — выбрать зуб', toothToggleClose: 'Скрыть схему зубов',
    evalLoading: 'Оценка готовится…', diagRight: 'Диагноз верный', diagWrong: 'Диагноз неверный', diagPartial: 'Диагноз частично верный',
    examTitle: 'Экзамен (20 вопросов)',
    examDesc: 'Вы отвечаете на все 20 вопросов. В конце вы увидите результат — с 18 правильными ответами вы сдали и переходите на следующий уровень.',
    examStart: 'Начать экзамен', cancel: 'Отмена',
    connectionError: 'Проблема с соединением — попробуйте ещё раз.',
    voiceNothingHeard: 'Ничего не распознано — скажите ещё раз.',
    voiceRecognitionFailed: 'Распознавание речи не удалось. Попробуйте снова.',
    voiceNoMic: 'Нет доступа к микрофону. Разрешите доступ в настройках.',

    quizCreating: 'Экзаменационные вопросы для этого случая создаются…',
    quizCreatingSub: 'Это может занять до 30 секунд — каждый раз генерируются заново.',
    exam: 'Экзамен', retry: 'Повторить', backToCase: 'Назад к случаю',
    notPassed: 'Не сдано', passed: 'Сдано', of: 'из',
    passNote: 'Для перехода нужно минимум {n} из {t} правильных ответов. Сначала посмотрите, что пошло не так:',
    restart: 'Начать заново', nextStage: 'Дальше, к следующему уровню →', repeatStage: 'Повторить этот уровень',
    question: 'Вопрос', confirmAnswer: 'Подтвердить ответ', next: 'Далее', finishExam: 'Завершить экзамен',
    correct: 'Верно.', incorrect: 'Неверно.',
    yourAnswer: 'Ваш ответ:', correctWouldBe: 'Правильно было бы:', deepenTopic: 'Изучить тему →',
    reviewMistakes: 'Это тоже стоит посмотреть:',
    toAccount: 'на практический счёт', xpUnit: 'опыта', levelUp: 'Новый уровень'
  },
  en: {
    navHome: 'Home', navPractice: 'Practice', navToday: 'Today', navMistakes: 'Mistakes', navCoach: 'Coach',
    account: 'Account', changeAvatar: 'Change profile photo',
    loggedInAs: 'Logged in as', memberSince: 'Member since', daysUnit: 'days', practicedOn: 'Practiced for', daysUnit2: 'days',
    targetState: 'Target state', myMistakes: 'My mistakes', dailyTraining: '10-minute training',
    aiCoach: 'AI learning coach', dashboard: 'Dashboard', logout: 'Log out',
    practiceAccount: 'Practice account', level: 'Level', practicedDaysTitle: 'Days practiced',

    diffLeicht: 'Easy', diffMittel: 'Medium', diffSchwer: 'Hard', diffPro: 'Pro',
    nextPatient: 'Next patient →', newCase: '✨ New case', caseCreating: 'Creating case…',
    voiceActive: '🎙️ Voice conversation: active', voiceStart: '🎙️ Start voice conversation',
    talkDone: '⏹ Done', talkSpeak: '🎤 Speak',
    patientSpeaking: 'Patient is speaking…', recording: 'Recording…', transcribing: 'Understanding…',
    listening: 'Listening…', oneMoment: 'One moment…',
    voiceHintPtt: 'Tap "Speak", say your sentence, then tap "Done". E.g. "Could you send me an X-ray?" or "My diagnosis is …"',
    voiceHintSr: 'Say e.g. "Could you send me an X-ray?" or "My diagnosis is …" — the conversation continues without pressing anything.',
    askPlaceholder: 'Ask your question…', askPlaceholderVoice: 'Voice mode active — or type here…',
    send: 'Send', requestImage: 'request', xrayNoun: 'X-ray', photoNoun: 'Photo',
    askSendXray: 'Could you please send me an X-ray?', askSendPhoto: 'Could you please send me a photo?',
    imgHint: 'In practice, diagnosis is usually based on an image — request it before entering your diagnosis.',
    yourDiagnosis: 'Your diagnosis (required for evaluation)', diagPlaceholder: 'e.g. Irreversible pulpitis, tooth 36',
    showEval: 'Show evaluation', enterDiagFirst: 'Please enter your diagnosis first.',
    toothToggleOpen: '🦷 Open tooth chart — select a tooth', toothToggleClose: 'Hide tooth chart',
    evalLoading: 'Preparing evaluation…', diagRight: 'Diagnosis correct', diagWrong: 'Diagnosis incorrect', diagPartial: 'Diagnosis partially correct',
    examTitle: 'Exam (20 questions)',
    examDesc: 'You answer all 20 questions. At the end you see your result — 18 or more correct means you passed and advance to the next stage.',
    examStart: 'Start exam', cancel: 'Cancel',
    connectionError: 'Connection problem — please try again.',
    voiceNothingHeard: 'Nothing understood — please speak again.',
    voiceRecognitionFailed: 'Speech recognition failed. Please try again.',
    voiceNoMic: 'No microphone access. Please allow it in settings.',

    quizCreating: 'The exam questions for this case are being created…',
    quizCreatingSub: 'This can take up to 30 seconds — they are freshly generated every time.',
    exam: 'Exam', retry: 'Retry', backToCase: 'Back to case',
    notPassed: 'Not passed', passed: 'Passed', of: 'of',
    passNote: 'You need at least {n} out of {t} correct answers to advance. First read what went wrong:',
    restart: 'Start over', nextStage: 'Continue to next stage →', repeatStage: 'Repeat this stage',
    question: 'Question', confirmAnswer: 'Confirm answer', next: 'Next', finishExam: 'Finish exam',
    correct: 'Correct.', incorrect: 'Incorrect.',
    yourAnswer: 'Your answer:', correctWouldBe: 'Correct answer:', deepenTopic: 'Explore this topic →',
    reviewMistakes: 'You should still look at these:',
    toAccount: 'to practice account', xpUnit: 'experience', levelUp: 'Level up'
  },
  tr: {
    navHome: 'Başlangıç', navPractice: 'Alıştırma', navToday: 'Bugün', navMistakes: 'Hatalar', navCoach: 'Koç',
    account: 'Hesap', changeAvatar: 'Profil fotoğrafını değiştir',
    loggedInAs: 'Giriş yapan', memberSince: 'Üyelik başlangıcı', daysUnit: 'gün', practicedOn: 'Çalışılan gün', daysUnit2: 'gün',
    targetState: 'Hedef eyalet', myMistakes: 'Hatalarım', dailyTraining: '10 dakikalık antrenman',
    aiCoach: 'Yapay zekâ koçu', dashboard: 'Kontrol paneli', logout: 'Çıkış yap',
    practiceAccount: 'Pratik hesabı', level: 'Seviye', practicedDaysTitle: 'Çalışılan günler',

    diffLeicht: 'Kolay', diffMittel: 'Orta', diffSchwer: 'Zor', diffPro: 'Pro',
    nextPatient: 'Sonraki hasta →', newCase: '✨ Yeni vaka', caseCreating: 'Vaka oluşturuluyor…',
    voiceActive: '🎙️ Sesli görüşme: Aktif', voiceStart: '🎙️ Sesli görüşmeyi başlat',
    talkDone: '⏹ Bitti', talkSpeak: '🎤 Konuş',
    patientSpeaking: 'Hasta konuşuyor…', recording: 'Kaydediliyor…', transcribing: 'Anlaşılıyor…',
    listening: 'Dinliyorum…', oneMoment: 'Bir dakika…',
    voiceHintPtt: '"Konuş"a dokunun, konuşun, sonra "Bitti"ye dokunun. Örn: "Bana bir röntgen gönderebilir misiniz?" veya "Teşhisim — …"',
    voiceHintSr: 'Örn: "Bana bir röntgen gönderebilir misiniz?" veya "Teşhisim — …" deyin — görüşme düğmeye basmadan devam eder.',
    askPlaceholder: 'Sorunuzu yazın…', askPlaceholderVoice: 'Sesli mod aktif — veya buraya yazın…',
    send: 'Gönder', requestImage: 'iste', xrayNoun: 'Röntgen', photoNoun: 'Fotoğraf',
    askSendXray: 'Bana bir röntgen gönderebilir misiniz?', askSendPhoto: 'Bana bir fotoğraf gönderebilir misiniz?',
    imgHint: 'Pratikte teşhis genellikle bir görüntüye dayanır — teşhisinizi girmeden önce isteyin.',
    yourDiagnosis: 'Teşhisiniz (değerlendirme için zorunlu)', diagPlaceholder: 'örn: Geri dönüşümsüz pulpitis, diş 36',
    showEval: 'Değerlendirmeyi göster', enterDiagFirst: 'Lütfen önce teşhisinizi girin.',
    toothToggleOpen: '🦷 Diş şemasını aç — diş seç', toothToggleClose: 'Diş şemasını gizle',
    evalLoading: 'Değerlendirme hazırlanıyor…', diagRight: 'Teşhis doğru', diagWrong: 'Teşhis yanlış', diagPartial: 'Teşhis kısmen doğru',
    examTitle: 'Sınav (20 soru)',
    examDesc: 'Tüm 20 soruyu yanıtlarsınız. Sonunda sonucunuzu görürsünüz — 18 veya daha fazla doğru cevapla geçersiniz ve bir sonraki aşamaya geçersiniz.',
    examStart: 'Sınavı başlat', cancel: 'İptal',
    connectionError: 'Bağlantı sorunu — lütfen tekrar deneyin.',
    voiceNothingHeard: 'Hiçbir şey anlaşılmadı — lütfen tekrar konuşun.',
    voiceRecognitionFailed: 'Ses tanıma başarısız oldu. Lütfen tekrar deneyin.',
    voiceNoMic: 'Mikrofon erişimi yok. Lütfen ayarlardan izin verin.',

    quizCreating: 'Bu vaka için sınav soruları oluşturuluyor…',
    quizCreatingSub: 'Bu işlem 30 saniyeye kadar sürebilir — her seferinde yeniden oluşturulur.',
    exam: 'Sınav', retry: 'Tekrar dene', backToCase: 'Vakaya dön',
    notPassed: 'Geçilemedi', passed: 'Geçildi', of: '/',
    passNote: 'İlerlemek için en az {t} sorudan {n} doğru gerekir. Önce neyin yanlış gittiğini okuyun:',
    restart: 'Baştan başla', nextStage: 'Sonraki aşamaya geç →', repeatStage: 'Bu aşamayı tekrarla',
    question: 'Soru', confirmAnswer: 'Cevabı onayla', next: 'İleri', finishExam: 'Sınavı bitir',
    correct: 'Doğru.', incorrect: 'Yanlış.',
    yourAnswer: 'Cevabınız:', correctWouldBe: 'Doğru cevap:', deepenTopic: 'Konuyu derinleştir →',
    reviewMistakes: 'Bunlara da bakmalısınız:',
    toAccount: 'pratik hesabına', xpUnit: 'deneyim', levelUp: 'Terfi'
  },
  ar: {
    navHome: 'الرئيسية', navPractice: 'تدريب', navToday: 'اليوم', navMistakes: 'الأخطاء', navCoach: 'المدرّب',
    account: 'الحساب', changeAvatar: 'تغيير صورة الملف الشخصي',
    loggedInAs: 'تم تسجيل الدخول باسم', memberSince: 'عضو منذ', daysUnit: 'يومًا', practicedOn: 'تم التدريب لمدة', daysUnit2: 'يومًا',
    targetState: 'الولاية المستهدفة', myMistakes: 'أخطائي', dailyTraining: 'تدريب 10 دقائق',
    aiCoach: 'المدرّب الذكي', dashboard: 'لوحة التحكم', logout: 'تسجيل الخروج',
    practiceAccount: 'حساب الممارسة', level: 'المستوى', practicedDaysTitle: 'أيام التدريب',

    diffLeicht: 'سهل', diffMittel: 'متوسط', diffSchwer: 'صعب', diffPro: 'محترف',
    nextPatient: 'المريض التالي ←', newCase: '✨ حالة جديدة', caseCreating: 'جاري إنشاء الحالة…',
    voiceActive: '🎙️ محادثة صوتية: نشطة', voiceStart: '🎙️ بدء محادثة صوتية',
    talkDone: '⏹ تم', talkSpeak: '🎤 تحدّث',
    patientSpeaking: 'المريض يتحدث…', recording: 'جارٍ التسجيل…', transcribing: 'جارٍ الفهم…',
    listening: 'أستمع…', oneMoment: 'لحظة من فضلك…',
    voiceHintPtt: 'اضغط على "تحدّث"، قل جملتك، ثم اضغط "تم". مثال: "هل يمكنك إرسال صورة أشعة؟" أو "تشخيصي هو …"',
    voiceHintSr: 'قل مثلاً: "هل يمكنك إرسال صورة أشعة؟" أو "تشخيصي هو …" — تستمر المحادثة دون الضغط على أي زر.',
    askPlaceholder: 'اكتب سؤالك…', askPlaceholderVoice: 'الوضع الصوتي نشط — أو اكتب هنا…',
    send: 'إرسال', requestImage: 'طلب', xrayNoun: 'الأشعة', photoNoun: 'الصورة',
    askSendXray: 'هل يمكنك أن ترسل لي صورة أشعة من فضلك؟', askSendPhoto: 'هل يمكنك أن ترسل لي صورة من فضلك؟',
    imgHint: 'في العيادة، يعتمد التشخيص عادةً على صورة — اطلبها قبل إدخال تشخيصك.',
    yourDiagnosis: 'تشخيصك (مطلوب للتقييم)', diagPlaceholder: 'مثال: التهاب لب لا رجعي، السن 36',
    showEval: 'عرض التقييم', enterDiagFirst: 'يرجى إدخال تشخيصك أولاً.',
    toothToggleOpen: '🦷 فتح مخطط الأسنان — اختر سنًا', toothToggleClose: 'إخفاء مخطط الأسنان',
    evalLoading: 'جارٍ إعداد التقييم…', diagRight: 'التشخيص صحيح', diagWrong: 'التشخيص خاطئ', diagPartial: 'التشخيص صحيح جزئيًا',
    examTitle: 'الاختبار (20 سؤالًا)',
    examDesc: 'ستجيب عن جميع الأسئلة العشرين. في النهاية سترى نتيجتك — 18 إجابة صحيحة أو أكثر تعني أنك نجحت وتنتقل إلى المرحلة التالية.',
    examStart: 'بدء الاختبار', cancel: 'إلغاء',
    connectionError: 'مشكلة في الاتصال — يرجى المحاولة مرة أخرى.',
    voiceNothingHeard: 'لم يتم فهم أي شيء — يرجى التحدث مرة أخرى.',
    voiceRecognitionFailed: 'فشل التعرف على الصوت. يرجى المحاولة مرة أخرى.',
    voiceNoMic: 'لا يوجد وصول إلى الميكروفون. يرجى السماح به في الإعدادات.',

    quizCreating: 'يتم إنشاء أسئلة الاختبار لهذه الحالة…',
    quizCreatingSub: 'قد يستغرق هذا حتى 30 ثانية — يتم إنشاؤها من جديد في كل مرة.',
    exam: 'الاختبار', retry: 'إعادة المحاولة', backToCase: 'العودة إلى الحالة',
    notPassed: 'لم يتم النجاح', passed: 'تم النجاح', of: 'من',
    passNote: 'تحتاج إلى {n} إجابة صحيحة على الأقل من أصل {t} للانتقال. اقرأ أولاً ما الذي حدث بشكل خاطئ:',
    restart: 'البدء من جديد', nextStage: 'الانتقال إلى المرحلة التالية ←', repeatStage: 'إعادة هذه المرحلة',
    question: 'سؤال', confirmAnswer: 'تأكيد الإجابة', next: 'التالي', finishExam: 'إنهاء الاختبار',
    correct: 'صحيح.', incorrect: 'خطأ.',
    yourAnswer: 'إجابتك:', correctWouldBe: 'الإجابة الصحيحة:', deepenTopic: 'تعمّق في الموضوع ←',
    reviewMistakes: 'يجب أيضًا مراجعة هذه النقاط:',
    toAccount: 'إلى حساب الممارسة', xpUnit: 'خبرة', levelUp: 'ترقية'
  }
};
